// Myanmar regions and townships data for hierarchical dropdowns

export const MYANMAR_REGIONS = [
  { id: 'yangon', name: 'Yangon' },
  { id: 'mandalay', name: 'Mandalay' },
  { id: 'naypyidaw', name: 'Naypyidaw' },
  { id: 'bago', name: 'Bago' },
  { id: 'ayeyarwady', name: 'Ayeyarwady' },
  { id: 'sagaing', name: 'Sagaing' },
  { id: 'magway', name: 'Magway' },
  { id: 'mon', name: 'Mon' },
  { id: 'rakhine', name: 'Rakhine' },
  { id: 'kayin', name: 'Kayin' },
  { id: 'kaya', name: 'Kaya' },
  { id: 'chin', name: 'Chin' },
  { id: 'shan', name: 'Shan' },
  { id: 'kachin', name: 'Kachin' },
];

export const TOWNSHIPS_BY_REGION: Record<string, string[]> = {
  yangon: [
    'Bahan',
    'Dagon',
    'Latha',
    'Pabedan',
    'Kyauktada',
    'Mingalar Taung Nyunt',
    'Kamayut',
    'Hlaing',
    'Mayangone',
    'Insein',
    'Thaketa',
    'South Okkalapa',
    'North Okkalapa',
    'North Dagon',
    'South Dagon',
    'East Dagon',
    'Thingangyun',
    'Mingaladon',
    'Shwepyithar',
    'Seikkyi Kanaungto',
    'Dala',
    'Twante',
    'Kawhmu',
    'Kungyangon',
    'Kayan',
    'Hlegu',
    'Taikkyi',
    'Hmawbi',
  ],
  mandalay: [
    'Aungmyaythazan',
    'Chanayethazan',
    'Mahaaungmye',
    'Chanmyathazi',
    'Pyigyidagun',
    'Amarapura',
    'Patheingyi',
    'Maha Aungmye',
    'Pyinoolwin',
    'Mandalay',
    'Madaya',
    'Singaing',
    'Kyaukse',
    'Myingyan',
    'Ngazun',
    'Taungtha',
    'Meiktila',
    'Mahlaing',
    'Thazi',
  ],
  naypyidaw: [
    'Zabuthiri',
    'Dekkhinathiri',
    'Pobbathiri',
    'Tatkon',
    'Ottarathiri',
    'Lewe',
    'Pyinmana',
    'Zeyathiri',
  ],
  bago: [
    'Bago',
    'Taungoo',
    'Pyay',
    'Thayarwady',
    'Kawa',
    'Waw',
    'Htantabin',
    'Oke Twin',
    'Shwegyin',
    'Kyonpyaw',
  ],
  ayeyarwady: [
    'Pathein',
    'Hinthada',
    'Myaungmya',
    'Maubin',
    'Bogale',
    'Kyaiklat',
    'Labutta',
    'Mawlamyinegyun',
    'Wakema',
    'Myanaung',
  ],
  sagaing: [
    'Sagaing',
    'Monywa',
    'Shwebo',
    'Katha',
    'Kale',
    'Tamu',
    'Mingin',
    'Khin-U',
    'Ye-U',
    'Kalay',
  ],
  magway: [
    'Magway',
    'Pakokku',
    'Thayet',
    'Aunglan',
    'Yenangyaung',
    'Chauk',
    'Taungdwingyi',
    'Minbu',
    'Natmauk',
    'Mindon',
  ],
  mon: [
    'Mawlamyine',
    'Thaton',
    'Kyaikmaraw',
    'Chaungzon',
    'Kyaikto',
    'Bilin',
    'Paung',
    'Ye',
    'Mudon',
    'Thanbyuzayat',
  ],
  rakhine: [
    'Sittwe',
    'Maungdaw',
    'Buthidaung',
    'Rathedaung',
    'Kyauktaw',
    'Ponnagyun',
    'Mrauk-U',
    'Minbya',
    'Myebon',
    'Kyaukpyu',
  ],
  kayin: [
    'Hpa-an',
    'Myawaddy',
    'Kawkareik',
    'Hpapun',
    'Thandaung',
    'Kya-in Seikkyi',
  ],
  kaya: [
    'Loikaw',
    'Demoso',
    'Pasaung',
    'Pruso',
    'Shadaw',
  ],
  chin: [
    'Hakha',
    'Falam',
    'Tedim',
    'Tonzang',
    'Matupi',
    'Mindat',
    'Kanpetlet',
  ],
  shan: [
    'Taunggyi',
    'Lashio',
    'Kengtung',
    'Muse',
    'Kyaukme',
    'Hsipaw',
    'Nyaungshwe',
    'Kalaw',
    'Pindaya',
    'Ywangan',
  ],
  kachin: [
    'Myitkyina',
    'Bhamo',
    'Putao',
    'Mohnyin',
    'Mogaung',
    'Waingmaw',
    'Chipwi',
    'Sumprabum',
  ],
};
